### ISSUE TITLE
I'd like to reproduce your work. 

### ISSUE THREAD

**Issue by ybh4798** [j3soon/dfac#1]
Could you upload your DFAC code? I also want to check the hyper-parameters to reproduce your results

**Comment by j3soon** [comment]
I'll upload the code within a few days. By the way, all hyperparameters are listed in the [supplementary materials](http://proceedings.mlr.press/v139/sun21c.html).

**Comment by j3soon** [comment]
The code is uploaded. Please ask me if you have any question.
