### ISSUE TITLE
how Figure 2 in the paper was drawn

### ISSUE THREAD

**Issue by LiP2301** [j3soon/dfac#2]
Hello, I have been very inspired by your article recently. But there is a question that is not very clear, how Figure 2 in the paper was drawn(especially Z1, Z2, and Zjt in Figure 2). The paper writes "_**As IQN approximates the utilities Z1 and Z2 implicitly, Z1, Z2, and Zjt can only be plotted in terms of samples**_.", but the output of IQN algorithm is quantile. Where did the sampled samples come from， and how to draw CDFs curve according to these quantile?

**Comment by j3soon** [comment]
$Z_k(s,u)$ is approximated by an implicit quantile function $F^{-1}_k(s,u|\omega)$.

We can plot the utility/return CDF under a certain state-action pair $(s,u)$ by sampling $\omega\sim U([0,1])$. Specifically, the x-axis corresponds to the output of $F^{-1}_k$, while the y-axis corresponds to $\omega$.

![fig2](https://user-images.githubusercontent.com/20457146/230542921-25156668-f4f6-49e8-92ba-eb6665886352.png)
